// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWldrao0SWebO7pnQRe2PnLwd9S9jlzUU',
    appId: '1:424094790164:web:0daf7e42891d521b43ed01',
    messagingSenderId: '424094790164',
    projectId: 'goodstudy-bac7a',
    authDomain: 'goodstudy-bac7a.firebaseapp.com',
    storageBucket: 'goodstudy-bac7a.appspot.com',
    measurementId: 'G-DP8WBFZZ95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByNgIYvYhKjOXhU3tolhpZ-6VkF4eMVVU',
    appId: '1:424094790164:android:76a7da89c020e22f43ed01',
    messagingSenderId: '424094790164',
    projectId: 'goodstudy-bac7a',
    storageBucket: 'goodstudy-bac7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYpkF4lTW3MnrfL-e_7h1qGHttG6Ht0-U',
    appId: '1:424094790164:ios:7677382aa9b79daf43ed01',
    messagingSenderId: '424094790164',
    projectId: 'goodstudy-bac7a',
    storageBucket: 'goodstudy-bac7a.appspot.com',
    iosBundleId: 'goodstudy.com.projetoGoodstudy',
  );

}